name: VSCode Server
on: workflow_dispatch

jobs:
  setup:
    name: My job
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
    - name: ğŸ› Debug Build
      uses: stateful/vscode-server-action@v1
      # if: failure()
      with:
        timeout: '7200000'
